name: Profile Summary Cards

on:
  # UTC 时间每月9号18:00（北京时间每月10号2:00）自动运行
  schedule:
    - cron: '0 18 9 * *'
  # 允许手动点击按钮运行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: main
          UTC_OFFSET: 8
          AUTO_PUSH: false

      - name: Setup Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push Changes
        run: |
          git add .
          if ! git diff --staged --quiet; then
            echo "Changes detected, committing..."
            git commit -m "Update profile summary cards"
            git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
          else
            echo "No changes detected, skipping commit."
          fi
